services:
  bluesky-store-locator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bluesky-store-locator
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
    volumes:
      # Mount data directory for persistence (optional)
      - ./server/data:/app/server/data
    restart: unless-stopped
    networks:
      - bluesky-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:5000/api/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  bluesky-network:
    driver: bridge

# Optional: Add a volume for data persistence
volumes:
  store-data:
    driver: local